### ISSUE TITLE
When do you do pull request to the neurodocker master?

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodocker#12]
Just wonder what is your plan with regard to that?
Will be good for us to have independence, but best to keep the master updated as much as possible.

**Comment by stebo85** [comment]
Currently neurodocker upstream is not moving forward and pull request's are not getting merged, so we have to manually pull in things from upstream if we need something, because we are ahead of upstream - not ideal, but I hope things get better in the future.
